README.md

The batching example had 'urlshortener' misspelled. If someone was to copy and paste the example to test it wouldn't work.

Fixing README.md spelling mistake

---

google-api-client.gemspec
lib/google/api_client.rb

This provides the simplest possible integration with googleauth, leaving other work items like removing the existing oauth2 implementation for later, when googleauth can handle all of that.  For now
- googleauth is not the default option, it needs to be selected by specifying authorization: google_app_default in the options
- the scope to use can be configured as an option as well

Adds simple integration with googleauth

---

lib/google/api_client.rb
lib/google/api_client/auth/key_utils.rb
lib/google/api_client/auth/storage.rb
lib/google/api_client/batch.rb
lib/google/api_client/request.rb
lib/google/api_client/service/simple_file_store.rb

This PR addresses several warnings that occur in the library. These warnings occur in projects that use google-api-client. The warnings addressed are:
* assigned but unused variable
* File.exists? is deprecated
* instance variable not initialized
* shadowing outer local variable
You can see these warnings by enabling the `-w` flag when running the specs.
`$ RUBYOPT=-w rake spec`
(There are several more warnings in the specs that are not addressed in this PR, as they will not show up when simply using the library.)

Fix warnings

---

.travis.yml
Gemfile
google-api-client.gemspec

Presumably the build matrix can be pruned depending on what combinations you feel safe leaving out.

Support and test under Rails 3.2, 4.0, 4.1, and 4.2

---

lib/google/api_client/discovery/api.rb
spec/google/api_client/discovery_spec.rb

Fixes #195
A number of Google APIs do not use `www.googleapis.com` as their base URI.  This patch reads the `'rootUrl'` from discovery documents to use as the host name for API requests, fixing request URLs for services such as Pub/Sub API, which hosts its endpoints on `pubsub.googleapis.com`.
Before this patch, the URL of the discovery doc ([`#document_base`](https://github.com/google/google-api-ruby-client/blob/master/lib/google/api_client/discovery/api.rb#L32)) was used as the root URL for [building service requests](https://github.com/google/google-api-ruby-client/blob/master/lib/google/api_client/discovery/api.rb#L151).  This exposes the `'rootUrl'` from discovery documents as [`Google::APIClient::API#root_uri`](https://github.com/remi/google-api-ruby-client/blob/1ed677b796afad92b5f23 …

Use discovered 'rootUrl' as base URI for services

---

lib/google/api_client/discovery/method.rb
spec/google/api_client/discovery_spec.rb

Update `Google::APIClient::Method#uri_template` to support discovered API methods including colons, eg. Pub/Sub `topics.publish`, `subscriptions.pull`, et al
Fixes #218

Respect discovered methods with colons in path

---

lib/google/api_client/result.rb

Updating the definition of SUCCESS response code to be **200 OK** or **201
Created**. Error is *anything* that is not success. This helps flag
conditions like an unsuccessful update (return code 304) which the
library would have flagged as success earlier

Updating success logic

---

CHANGELOG.md
lib/google/api_client.rb
lib/google/api_client/service.rb

There was a small discrepency around Google::ApiClient api It was :
- `:faraday_options` in the inline documentation and in the Changelog
- `:faraday_option` in the actual code and specs
This PR make it uniform and use  `:faraday_option` to be backward compatible.
I also added the option to Google::ApiClient::Service as it was not yet supported there.

Fix discrepency around faraday_option and add it to APIClient::Service

---

spec/integration_tests/drive_spec.rb
spec/integration_tests/pubsub_spec.rb
spec/integration_tests/url_shortener_spec.rb
spec/spec_helper.rb

Small set of integration tests to run against live APIs and verify basic functionality in the API (basic requests, upload/download, batching, etc.) Not intended to be a comprehensive suite of tests, but may grow over time.
Requires setting the environment variables GOOGLE_APPLICATION_CREDENTIALS (as in application default credentials) and GOOGLE_PROJECT_ID.

Initial set of integration tests against live APIs

---

README.md

A gem 'google-api-client' will give the developer version 0.8.6, not 0.9. The smallest solution is to update the readme. This better communicates that the gem is going through some large changes.

Clearly specifying 0.9 as the current version

---

Gemfile
samples/drive/drive.rb

To ```upload_source``` me must setup full path to file
```ruby
$ bundle exec ruby samples/drive/drive.rb
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/hurley-0.1/lib/hurley/multipart.rb:33:in `initialize': No such file or directory - drive.rb (Errno::ENOENT)
from /usr/local/rvm/gems/ruby-2.0.0-p598/gems/hurley-0.1/lib/hurley/multipart.rb:33:in `open'
from /usr/local/rvm/gems/ruby-2.0.0-p598/gems/hurley-0.1/lib/hurley/multipart.rb:33:in `initialize'
```
So fix it + add debug gems to Gemfile

fix drive example + add debug gems for dev

---

lib/google/apis/options.rb
spec/google/apis/options_spec.rb

Here
```
%w(authorization retries timeout_sec).each do |opt|
```
there is no ```header``` option
Also, all this keys we can get with [Struct#members](http://ruby-doc.org/core-2.2.0/Struct.html#method-i-members) method.
Also, add method for overriding default options.

fix RequestOptions#merge + test for default options

---

lib/google/apis/core/upload.rb
spec/google/apis/core/upload_spec.rb

`Tempfile` is not subclass of `IO`. it is subclass of `Delegator`.
Because of it, `Tempfile` instance is regarded as invalid source.
I think that `Tempfile` is useful to upload to bigquery.
API client should be able to use `Tempfile` object.

Add Tempfile to if statement of BaseUploadCommand#prepare!

---

lib/google/apis/core/upload.rb

Otherwise I get:
gems/google-api-client-0.9/lib/google/apis/core/upload.rb:104:in `streamable?': uninitialized constant Google::Apis::Core::BaseUploadCommand::Tempfile (NameError)
when do
service.insert_file(metadata, upload_source: "temp.pdf")

required 'tempfile'

---

samples/cli/lib/samples/androidpublisher.rb

Add basic example for androidpublisher_v2 API. Upload an apk to Google Play.

Add sample: androidpublisher

---

lib/google/apis/core/api_command.rb

`/[\w_]+/` is equivalent to `/\w+/`. 
> /\w/ - A word character ([a-zA-Z0-9_])
Ruby-doc [reference](http://ruby-doc.org/core-2.3.0/Regexp.html#class-Regexp-label-Character+Classes).
This will fix the warning when running `ruby -vr google/apis/drive_v3 -e ''`: 
```
/path/to/gems/google-api-client-0.9.1/lib/google/apis/core/api_command.rb:130: warning: character class has duplicated range: /[\w_]+/
```

Cleaner code on regexp

---

README.md

The original samples link pointed to the (now) out of date examples for version 0.8 of this gem. I lost a few hours wondering why things were not working.
Hoping to save someone else the time I lost (and reap the karmic bounty thereof).

Update 'samples' link to 'samples' folder

---

lib/google/apis/core/http_command.rb

In current version, developer cannot change connection timeout of httpclient per API request.
google-api-ruby-client always uses default value (20 sec).
For example
```ruby
Bigquery.client.insert_job(
Bigquery::PROJECT_ID,
{
configuration: {
load: {
destination_table: {
project_id: Bigquery::PROJECT_ID,
dataset_id: Bigquery::DATA_SET,
table_id: "test",
},
schema: {
fields: [
{
name: "id",
type: "STRING",
mode: "REQUIRED"
},
{
name: "timestamp",
type: "TIMESTAMP",
mode: "NULLABLE"
},
]
},
}
}
},
{upload_source: File.open("./upload_source.log"), content_type: "application/octet-stream", options: {timeout_sec: 300, open_timeout_sec: 300}},
```
I set RequestOptions, but httpclient uses default `open_timeout_sec`.
this is very troubled when I upload a large file to Bigquery.
Even if …

Assign `open_timeout` option in `apply_request_options`

---

bin/generate-api
google-api-client.gemspec
lib/google/api_client/client_secrets.rb
lib/google/apis/core/api_command.rb
lib/google/apis/generator/annotator.rb
spec/google/api_client/client_secrets_spec.rb

JSON has been part of the ruby stdlib since 1.9.0 (see https://github.com/ruby/ruby/commit/af1c4167), and the latest version of this gem requires ruby 2.0 or better.
Would you consider removing multi_json as a dependency, and just using `require 'json'` instead? Rails recently made a similar change (https://github.com/rails/rails/pull/23453), which has prompted other libraries to consider the same issue (like [simplecov](https://github.com/colszowka/simplecov/issues/458) and [stripe](https://github.com/stripe/stripe-ruby/pull/379)).
See also this recent [blog post](http://www.mikeperham.com/2016/02/09/kill-your-dependencies/).

replace multi_json dependency with regular stdlib JSON

---

lib/google/apis/core/json_representation.rb
spec/google/apis/core/json_representation_spec.rb

current version sends `false` value as `nil` if given request parameter is Hash.
because of it, developler cannot change several options that are boolean type and default `true`.
For example `flatten_results` of Bigquery API,
```ruby
Bigquery.client.insert_job(
Bigquery::PROJECT_ID,
{
configuration: {
query: {
flatten_results: false,
query: "SELECT 1",
}
}
}
)
```
I expects
```json
{"configuration": {"query": {"flattenResults": false, "query": "SELECT 1"}}}
```
But actual request parameter is
```json
{"configuration": {"query": {"flattenResults": null, "query": "SELECT 1"}}}
```

Fix Hash value assignment in JsonSupport#getter_fn

---

google-api-client.gemspec

google-api-ruby-client requires ruby > 2.0 due to the use of `__dir__`, and potentially other code.
This documents issue #387 in the gemspec, at least.

Set required ruby version > 2.0

---

README.md

[Google Auth](https://github.com/google/google-auth-library-ruby) supports environment variables as a means of authorizing service apps. Add this technique to the docs for the benefit of others. Issue [#370](https://github.com/google/google-api-ruby-client/issues/370)

Add an authorization technique to the docs using env vars

---

google-api-client.gemspec

* Do not distribute test files
* Do not distribute the intermediate api_names_out.yaml file
> Reduces the packaged gem size from 1.8Mb to 1.6Mb
The practice of not distributing test files with a gem was originally
discussed and adopted by the Bundler team here:
https://github.com/bundler/bundler/pull/3207

Package fewer files in the gem

---

google-api-client.gemspec
spec/google/api_client/client_secrets_spec.rb

In ruby 2.0, the default encoding is UTF-8, so these magic comment
directives can be safely removed.
https://www.ruby-lang.org/en/news/2013/02/24/ruby-2-0-0-p0-is-released/

Remove comments specifying encoding

---

lib/google/api_client/client_secrets.rb
spec/google/api_client/client_secrets_spec.rb

Because of my production environment, adding a JSON file a little bit of a pain. However: using the `ClientSecrets` initialiser I set my credentials manually from my environment variables. I noticed that while all the credential details can be either a String or a Symbol, the 'flow' (i.e., `web`) **must** be a string.
This allows  to accept both a string and a symbol, which feels a little better to me because of the consistency.

Google::APICilent::ClientSecrets Allow symbols for credential `flow`

---

spec/google/api_client/auth/storages/file_store_spec.rb

`Google::APIClient::FileStore.load_credentials` loads all attributes of the json.

Modify  a spec for Google::APIClient::FileStore.load_credentials

---

README.md

This just bit me because of an ```uninitialized constant Google::Apis::Core::JsonObjectSupport``` error with generated API files, so I thought I would fix this up for someone in the future.
For dependency resolution, this specifies any version of 'google-api-client' 0.9 is valid, but 1.0 is not.

Use twiddle-wakka for dependency example in Gemfile

---

google-api-client.gemspec

thor is used only to generate the api folder.

remove thor as runtime dependency

---

.travis.yml

Rails 4.2.0 no longer supports Ruby 2.0.0, so this commit excludes it
from Travis builds.

Remove unsupported build matrix entry in Travis

---

lib/google/apis/core/api_command.rb
lib/google/apis/errors.rb
spec/google/apis/core/api_command_spec.rb

A `Google::Apis::ClientError` currently indicates that a request is invalid and should not be retried without modification. `check_status` in `Google::Apis::Core::ApiCommand` however, is returning this error for both retriable and non-retriable errors, such as `reviewQueryQuotaExceeded` and `projectNotLinked` respectively. 
This is not only incorrect, but the implementation makes it difficult for consumers to decide what to do without pattern matching against the error message.
This pull request takes the existing whitelisting logic for handling rate limit errors, and makes it more generic to support handling other types of errors.

Update check_status to better support different types of errors

---

google-api-client.gemspec

`Retriable` 3.0 involves changes to gem configuration that this gem doesn't make use of.

Allow retriable 3.0

---

samples/cli/lib/samples/you_tube.rb

In the sample code of v0.7, the keys of metadata was written in camel-case, but I have to write in snake-case in current version of the SDK. I have added an attribute to the sample code to guide users to use snake-case.
https://developers.google.com/youtube/v3/code_samples/ruby?hl=ja#upload_a_video
- the sample code for the current version is posted here.
https://github.com/google/google-api-ruby-client/issues/302#issuecomment-152264147

add attriubte to the metadata of youtube uploader sample

---

.travis.yml
google-api-client.gemspec
lib/google/apis/core/api_command.rb
lib/google/apis/core/json_representation.rb
spec/google/apis/core/json_representation_spec.rb

Also fixes a breaking change introduced between `representable` 2.3 and
3.0. Specifically, `:skip_undefined` is now be passed via the
`:user_options` option.
Resolves #483

Bump `representable` dependency to 3.0

---

MIGRATING.md

Migrating from 0.8 to 0.9 has been an extremely painful process, I will also add a full sample for using Google::Auth::ServiceAccountCredentials

Update Migrating guide

---

api_names.yaml

It seems the beginning of quotation was forgotten at line 346 of api_names.yml. Sorry for the small pull request.

Fix typo of api names yaml

---

lib/google/apis/core/base_service.rb
lib/google/apis/generator/templates/service.rb.tmpl
spec/fixtures/files/test_api.json
spec/google/apis/core/service_spec.rb
spec/google/apis/generator/generator_spec.rb

Fixes #523, though APIs will need to be regenerated after this.
Googlers: See b/32514652 for reference.

Update generator to use batchPath instead of hardcoded path

---

spec/integration_tests/adsense_spec.rb

Added integration test for AdSense to verify that a report with duplicate query string params is downloaded correctly.

Added integration test for AdSense 

---

lib/google/apis/core/api_command.rb
lib/google/apis/core/json_representation.rb
lib/google/apis/options.rb
spec/google/apis/core/api_command_spec.rb

Adds opt-in to use v2 error messages (google/google-api-ruby-client#544). Also fixes the `to_json` signature for compatibility with the `json` gem  (google/google-api-ruby-client#576)

Allow using v2 error messages + fix to_json signature 

---

lib/google/apis/core/base_service.rb
spec/google/apis/core/service_spec.rb

This commit aligns the behavior of `fetch_all` over map responses with
that of arrays (returning a single collection with all entries).
Fixes https://github.com/google/google-api-ruby-client/issues/584

Add Hash support to fetch_all

---

lib/google/apis/generator.rb
lib/google/apis/generator/annotator.rb

If the method name is generated from the request type, there is a
possibility of a clash if two methods take the same request type. For
example, if two unique methods take the request type
"CreateRoleRequest", both methods will be generated with the method name
"create_role", which causes generation to fail with an exception.
This commit resolves that issue by first generating a method name from
the request type of each method, and keeping track of which names are
duplicates. For methods that will generate a duplicate name from the
request type, the name is generated from the method ID instead (the
resulting name is guaranteed to be unique).

Allow automatic method name clash resolution

---

lib/google/apis/core/http_command.rb
spec/google/apis/core/http_command_spec.rb

Fixes https://github.com/google/google-api-ruby-client/issues/554

Allow auth retry on Signet::AuthorizationError

---

lib/google/apis/core/json_representation.rb

While reading the source file documentation I spotted this little typo.

Fix little typo on docs

---

.travis.yml
lib/google/apis/version.rb
spec/google/apis/core/service_spec.rb
spec/google/apis/versions_spec.rb

Hi there!
Accordingly, to this commit https://github.com/ruby/ruby/commit/0078e40115fd53e2cafd4e8cfb6ff5fd7f87c3db, multiline headers are no more acceptable.  It's a pity, but the library generates `User-Agent`  with OS version which contains trailing newline. 
This PR solves the issue and add explicit Ruby 2.4 and 2.5 support to test against on CI.

Add Ruby 2.5 support

---

README.md

For readers following the README's sequence of instructions to get logging to STDOUT/STDERR, they will generally add code in the order which it appears in the README. That results in this:
```
Google::Apis.logger.level = Logger::DEBUG
Google::Apis.logger = Logger.new(STDERR)
```
However, this configuration will not have the desired effect in Rails apps, since the newly created logger will not respect the log level which was actually set on the Rails logger. By changing the order in which these code snippets appear in the README, we can help readers avoid this gotcha.
Additionally, I offer a small semantic improvement to help readers better understand the two options they have for changing the default logger.

Improve language in Logging section of README

---

lib/google/apis/generator/helpers.rb

I found the bug, I am not familiar enough Ruby to make the fix idiomatic and I haven't looked for other acronym edge cases yet.
CC @Temikus

WIP: Change IPv4 to Ipv4 before interpetting it as camel case.

---

.gitignore
Gemfile
lib/google/apis/core/http_command.rb
spec/google/apis/generator/generator_spec.rb

It looks like the logging gem used to be in the bundle implicitly due to a transitive dependency, but has been removed. This is why the tests have been breaking. Adding it explicitly because the spec helper requires it.

Add logging to gemfile to fix specs

---

CHANGELOG.md
google-api-client.gemspec
lib/google/apis/version.rb

* Fix for https://github.com/google/google-api-ruby-client/issues/708
* Makes runtime dependency on signet explicit with correct version

update signet dependency

---

google-api-client.gemspec
lib/google/apis/core/http_command.rb

Similar to https://github.com/google/google-api-ruby-client/pull/707
As asked by @TheRoyalTnetennba in https://github.com/google/signet/pull/101
This PR adds the new `UnexpectedStatusError`

Add Signet::UnexpectedStatusError

---

Gemfile
spec/google/apis/core/http_command_spec.rb

Update the generated method name corresponding to `monitoring.projects.timeSeries.create` to `create_project_time_series`. This should fix the error that is currently causing Ruby codegen to break.
Currently, for some reason, the name map is mapping `monitoring.projects.timeSeries.create` to `create_time_series`, which is not the standard name normally generated for such a resource call. This is now breaking codegen because an update to the discovery doc introduced `monitoring.timeSeries.create`, which by default maps to `create_time_series`, resulting in a name conflict. This change reverts the mapping for `monitoring.projects.timeSeries.create` to the method name `create_project_time_series` that should normally be created for this call.
Despite the name change, this actually should …

Fix naming of monitoring.projects.timeSeries.create method

---

google-api-client.gemspec

Allow the dependency to use the 0.7.x releases.

Update googleauth dependency

---

lib/google/apis/errors.rb

Add the `status_code`, `header`, and `body` values to `#inspect` when present. These values can help users understand why they are getting errors, but many users don't know to look for them. Adding the values to inspect should help discoverability.
This change turns this:
```
#<Google::Apis::ClientError: timeRangeEmpty: The specified time range is empty.>
```
into this:
```
#<Google::Apis::ClientError: timeRangeEmpty: The specified time range is empty. status_code: 400 header: #<HTTP::Message::Headers:0x00007fee7d0352f0 @http_version="1.1", @body_size=221, @chunked=false, @request_method="GET", @request_uri=#<Addressable::URI:0x3ff73ce68e80 URI:https://www.googleapis.com/zoo/animals?>, @request_query=nil, @request_absolute_uri=nil, @status_code=400, @reason_phrase="Bad Request", …
```

Add custom inspect to Google::Apis:Error

---

lib/google/apis/core/download.rb
spec/google/apis/core/download_spec.rb

According to the documentation the destination IO only needs to respond to `#write`. However, the downloader breaks this by calling `#flush`. It so happens that I wanted to use a download destination which responds only to #write.
This PR fixes this by calling `#flush` on the destination IO only if it responds to it. We also add a test to enforce that the destination IO only needs to respond to `#write`.

Allow download destination to only respond to #write

---

lib/google/api_client/auth/installed_app.rb

Fixes #537
The `installed_app.rb` file is not really part of the library and arguably doesn't belong here. It is correctly deprecated. However, if it is loaded (possibly as a result of being eagerly loaded by ActiveSupport), and the `launchy` gem (which is not listed as a gem dependency so is not generally brought into user bundles) is not present, the file will crash with a `LoadError`.
So we do two things.
* Rescue the `LoadError` that results from `launchy` not being present, warn the user what has taken place, and bail from loading the rest of the file. This will let applications that use `eager_load` use the gem without having to include `launchy` in their bundle explicitly.
* Document the `launchy` dependency in case someone actually wants to use this (deprecated) class.

Prevent errors loading deprecated installed_app file if launchy is not present

---

Gemfile

Update version to address [vulnerability](https://nvd.nist.gov/vuln/detail/CVE-2017-8418).

Update Rubocop dependency

---

google-api-client.gemspec

Loosen the googleauth dependency to allow future changes. The team supporting googleauth has committed to not change backwards compatibility before 0.10.0.

Loosen googleauth dependency

---

lib/google/apis/core/http_command.rb
spec/google/apis/core/http_command_spec.rb

Change logged representation of the `Google::Apis::CloudkmsV1::DecryptResponse` class to remove all field data from the logged string.

Change logged representation of certain classes

---

lib/google/apis/core/http_command.rb
spec/integration_tests/cloudkms_spec.rb

Remove field data from logged HTTP response objects when the response type is in the blacklist. Follow-up to #752

Redact response logs for certain cases

---

lib/google/apis/core/http_command.rb
spec/google/apis/core/http_command_spec.rb

We have received word that a bad proxy setting can cause this behavior.
[fixes #764]

Handle bad response errors without response object

---

lib/google/apis/generator/model.rb
spec/google/apis/generator/generator_spec.rb

`Hash#reject!` is equivalent to `Hash#delete_if`, but returns nil if no changes were made.
Resolves #767

Fix exception when API desc doesn't include parameters

---

google-api-client.gemspec
spec/spec_helper/load_path_spec.rb

This directory was used when the gem was patching other gems,
like Hurley. But now this directory has been removed.

Remove third_party directory from gemspec

---

lib/google/apis/core/json_representation.rb
spec/google/apis/core/json_representation_spec.rb

According to https://www.rubydoc.info/github/google/google-api-ruby-client/Google/Apis/CalendarV3/EventDateTime#date-instance_method the ```date``` should be parsed to a ```Date```, but currently it is only a "yyyy-mm-dd" string.

Deserialize type: Date values

---

bin/generate-api

Pass the `names_out` value to the generator as the `api_names_out` argument. This is an attempt to resolve #623.

Fix generate-api names_out usage

---

google-api-client.gemspec
lib/google/apis/core/upload.rb

Replaced mime-types with mini_mime. Specs are passing.

Replace mime-types dependency with mini_mime

---

README.md

Adds a Rubydoc badge so developers can view docs.

docs: Add RubyDoc Badge

---

lib/google/apis/core/json_representation.rb
spec/google/apis/core/json_representation_spec.rb

Fixes #585 
Works around an issue with the `representable` gem where it doesn't pass JSON serialization options through its `to_json` implementation.

Support JSON serialization options for model objects

---

lib/google/api_client/client_secrets.rb

Ensure `googleauth` has loaded and its extensions to `signet` are in place when loading auth objects from `ClientSecrets`. Fixes #499

Ensure ClientSecrets uses googleauth extensions

---

lib/google/apis/core/http_command.rb
spec/google/apis/core/http_command_spec.rb

Ensure query parameters get converted explicitly to strings, to ensure there is proper support for passing `DateTime` and similar values to APIs. Fixes #755

Convert query values explicitly to strings

---

lib/google/apis/core/api_command.rb
spec/google/apis/core/api_command_spec.rb
spec/google/apis/core/service_spec.rb

Cause all API calls to set the X-Goog-Api-Client header, which is used for backend analytics.

Send x-goog-api-client header in all requests

---

lib/google/apis/core/batch.rb
spec/google/apis/core/batch_spec.rb

Supports OAuth token strings and googleauth/signet objects on individual batch calls by using `HttpCommand#apply_request_options` to add the Authorization header. Also add some test coverage for individual batch calls with auth set.
[closes #817]

Use auth objects for batch request auth

---

api_names.yaml

Codegen has been failing since Aug 26 because two calls (`/domainsrdap:v1/domainsrdap.getIp` and `/domainsrdap:v1/domainsrdap.ip.get`) in the new domainsrdap client are mapping to the same method name (`get_ip`). Overriding the mapping of the latter to `ip_get`. (Note that according to the [documentation](https://developers.google.com/domains/rdap/reference/rest/v1/ip/get) this call is not supported anyway and always returns a 5xx.)

fix: Customize name for an unsupported domainsrdap call

---

spec/google/apis/core/service_spec.rb

I don't think these are related at all to the current CI failures, but here are two fixes to the specs that are causing other issues.
* One matcher puts an OS name/version string in a Regexp, but in some environments (such as my local Linux) this string contains Regexp special characters (notably `+`). Escape the string before embedding in a Regexp.
* A second matcher is checking for the body posted in an http request, and includes a `Content-Length` header. This header's value depends on the ruby version and the gem version, and started failing when the gem version's length changed (`0.30.9` -> `0.30.10`). Change the matcher to match on a regexp instead of a literal string, and loosen the check on `Content-Length`.

Several fixes to specs

---

google-api-client.gemspec

Update the Ruby dependency to at least 2.4. Also update to the corresponding versions of signet and googleauth.
Note: This should not be merged until the build process is running on an updated Ruby. See https://github.com/googleapis/discovery-artifact-manager/pull/133

Require Ruby 2.4

---

lib/google/apis/core/upload.rb

If a resumable upload request has no associated JSON request document, initialize the request body to the empty string. This prevents HttpCommand from thinking that the intent is to form-encode the query parameters (which should never be done for upload requests).
Fixes #606.

fix: Prevent upload requests from form-encoding their queries

---

.kokoro/continuous/post.cfg

- Runs linkinator against repo and ref docs on the "post" job every merge-to-master

chore: add config for post job

---

lib/google/apis/core/api_command.rb
spec/google/apis/core/api_command_spec.rb

fix: Remove duplicate clauses in X-Goog-Api-Client header

---

docs/oauth-web.md

After comparing `docs/oauth-web.md` content with the cross-platform guide [Using OAuth 2.0 for Web Server Applications](https://developers.google.com/identity/protocols/OAuth2WebServer), I realized that in my original PR I failed to correctly adapt some content from #796 to `docs/oauth-web.md`. This PR adds that content.

docs: restore missing examples to oauth-web.md

---

CHANGELOG.md

Hello! 👋 This is a quick addition to the changelog to document the recent change in Ruby support.
From what I've been able to verify, it looks like 0.33.0 was the last time Ruby < 2.4 was supported. Introduced in #834 and verified with:
```
$ git tag --contains bc573bf98 | head -n1
0.33.0
```

Document Ruby compatibility change in changelog

---

lib/google/apis/core/http_command.rb
spec/google/apis/core/upload_spec.rb

The `ResumableUploadCommand` subclass does not use the normal `@http_res` result. As a result, `HttpCommand#opencensus_end_span` was throwing an internal exception and wasn't ending the span correctly, throwing the span stack out of sync and causing any caller's attempt to end the span to fail. This PR corrects the error.
Fixes #850

fix: Prevent OpenCensus integration from getting out of sync on upload commands

---

api_list_config.yaml
api_names.yaml
bin/generate-api
lib/google/apis/generator/annotator.rb

Apiary client generation has been broken for several weeks. The culprit, it appears, is the Apigee V1 discovery doc which is malformed. This PR adds a mechanism to temporarily blacklist individual APIs, and adds Apigee to that blacklist.
This also:
* Adds a couple of custom mappings for Spanner V1 which is currently experiencing name conflicts.
* Temporarily comments out a log message that is not very useful but is overwhelming the logs and making it difficult to see anything else. I'm leaving it commented for the time being rather than removing it outright, because I'm not yet sure what should be done in this case (e.g. whether this really is a warning case that should be paid attention to.)

fix: temporarily disable Apigee V1 and resolve conflicts in Spanner V1.

---

api_list_config.yaml
bin/generate-api
script/generate

* Apigee V1 discovery doc has reportedly been fixed upstream, so removing it from the exclusion list.
* Generation has been failing for some time. The logs for yesterday's run suggest that we're getting a server error from discovery for some libraries, which currently is causing the entire generation run to abort. Instead, just skip the offending library to allow others to proceed.
* Remove an obsolete library from the list of "special" discovery URLs.

Re-enable Apigee V1 and make generation more robust against discovery errors

---

lib/google/apis/version.rb

Closes: https://github.com/googleapis/google-api-ruby-client/issues/880
References: 
- article stating the problems with using backticks https://www.hilman.io/blog/2016/01/stop-using-backtick-to-run-shell-command-in-ruby/
- discussion about deprecating backticks in ruby 3 (even though the proposal was rejected it is an interesting read) https://bugs.ruby-lang.org/issues/14385
This PR updates `version.rb` to use the safer `Open3` instead of backticks which is vulnerable to command injection when determining the `OS_VERSION`.

Switch to safer Open3 to determine OS_VERSION

---

lib/google/apis/core/api_command.rb
lib/google/apis/options.rb
spec/google/apis/core/api_command_spec.rb

Allow user override of the quota project via request option.
Part of a Q2 Yoshi OKR.

feat: Support custom quota_project in request options

---

google-api-client.gemspec

Ruby master branch recently bumped the version number to 3.0: https://github.com/ruby/ruby/commit/21c62fb670b1646c5051a46d29081523cd782f11
This is breaking our ruby-head CI.

Update ruby_version requirement to allow ruby 3.0

---

google-api-client.gemspec

Refer this pull request and the discussion:
- Remove rexml and rss
https://github.com/ruby/ruby/pull/2832
- Feature #16485
https://bugs.ruby-lang.org/issues/16485
> Cons: The users need to add rexml to their Gemfile after Ruby 2.8(3.0)
Fixes #871

rexml is bundled gem in Ruby 3

---

.gitignore
api_list_config.yaml
bin/generate-api
script/generate
script/synth.rb
synth.py

This prepares google-api-ruby-client to generate using autosynth, by adding a synth script front-end to the generator. The intended usage is for every api/version combination to be synthesized separately, in order for each individual client regeneration to show up as a separate conventional commit item, and in preparation for later splitting the monolibrary into separate libraries for each api/version combination.
Details:
* Added two command line options to the `bin/generate-api` entrypoint:
* `--api=<API.VERSION>` specifying a particular api/version combination to generate. This will be the main entrypoint used by synthtool jobs to regenerate individual libraries.
* `--clean` which goes through existing generated client directories and deletes any that are not present in the discovery …

chore: Add synth scripts for client generation

---

lib/google/apis/core/api_command.rb

fix: Fix JSON parser crash if an empty body (such as HTTP 204) is received

---

lib/google/apis/core/http_command.rb
lib/google/apis/options.rb
spec/google/apis/core/http_command_spec.rb

Expose the ability for the user to configure HTTP URL parameters to be sent with every request.
```rb
service = API::BigqueryService.new
service.request_options.query ||= {}
service.request_options.query["prettyPrint"] = false
```
refs: googleapis/google-cloud-ruby#7806

feat: Add query to RequestOptions

---

.github/workflows/release-please.yml

Configure release-please for this repo.
Although this repo currently includes only one gem, it is configured as a monorepo (and hence its tag format includes a package name, which is currently set to `google-api-ruby-client` as a pseudonym). This is because it will shortly be broken out into multiple gems.
This workflow will eventually run on a weekly cron (rather than on every push to the main branch). However, this PR disables the cron temporarily, until I have the chance to test the workflow manually.

chore: Configure release-please-action

---

.github/workflows/release-please.yml

* Use `@v2` to get the latest v2 release-please-action instead of pinning to a specific release.
* Recent release-please releases should no longer attempt to add labels to the PR if `fork: true` is set. Therefore, this step will no longer fail due to permissions (since we are using `YOSHI_CODE_BOT_TOKEN`) and we no longer need to use `always()` as the guard for the next step.
* Recent release-please-action releases provide the created PR number as an output. We can use that, rather than having to search for the PR.

chore: Update release-please action to take advantage of upstream fixes

---

README.md

After moving google-api-client into a subdirectory.

Fixing README.md links

---

.github/workflows/release-core.yml
.github/workflows/release-generator.yml
.github/workflows/release-umbrella.yml

Previously, this repo had a single package located at the root. Now we have multiple packages located in subdirectories.
This PR modifies the release-please GitHub actions to cover the three packages that will be managed via release-please. The new actions are mostly the same as the original action, except the package names have been changed, and I've set the `path` parameter, which I assume tells release-please to limit its commit search to that subdirectory. (@bcoe is that right?)

chore: Update release-please jobs to reference separate gems

---

.repo-metadata.json
google-api-client/.repo-metadata.json
google-apis-core/.repo-metadata.json
google-apis-generator/.repo-metadata.json

Deleted the .repo-metadata.json from the root and add them to the three handwritten libs(core, client, and generator). This is part of internal issue #184315365.

chore: add .repo-metadata.json files to the three handwritten libs

---

google-apis-core/google-apis-core.gemspec

We've been asked to bump googleauth to 1.0. In preparation, we're expanding all googleauth dependencies to support both 0.x and 1.x.

fix(core): Expand googleauth dependency to include future 1.x versions

---

google-apis-core/lib/google/apis/core/base_service.rb
google-apis-core/spec/google/apis/core/service_spec.rb

fix(core): Prevent duplicated pagination when a response returns an empty string as the next page token

---

google-apis-generator/lib/google/apis/generator/templates/overview.md.tmpl

`client` only has a [authorization=](https://github.com/googleapis/google-api-ruby-client/blob/main/google-apis-core/lib/google/apis/core/base_service.rb#L151) method,  no `authentication` method. So, here, it guess it should be `authorization`

Update overview.md.tmpl - client only has `authorization=` method, no `authentication=`

---

google-apis-core/lib/google/apis/core/http_command.rb
google-apis-core/lib/google/apis/options.rb
google-apis-core/spec/google/apis/core/http_command_spec.rb
google-apis-core/spec/google/apis/options_spec.rb

By default, the Retriable gem sets `max_elapsed_time` to 15
minutes. This can result in large transfers being aborted prematurely
rather than being retried. Make it possible to configure this value in
case the default is too low.
Closes https://github.com/googleapis/google-api-ruby-client/issues/690

Support configuration of max elapsed time of requests

---

google-apis-core/lib/google/apis/core/http_command.rb

Atm almost all logs from the core api are debug logs. The default level for the logger is set to warn meaning, we see almost nothing at the beginning and it gets to verbose as soon as we reach the debug level.
This is not practical to debug real errors that why I'm proposing to change the level of this error log to error from debug

Properly log errors as errors

---

google-apis-core/lib/google/apis/core/http_command.rb

Reverts googleapis/google-api-ruby-client#6494

Revert "Properly log errors as errors"

---

google-apis-core/lib/google/apis/core/storage_upload.rb
google-apis-core/spec/google/apis/core/storage_upload_spec.rb

Fixes [#19246](https://github.com/googleapis/google-cloud-ruby/issues/19246)

fix(core): Storage upload to handle empty string/file cases

---

google-apis-core/lib/google/apis/core/batch.rb

The `length` variable is defined but never used.
This variable had been unused since 2017.
ref: https://github.com/googleapis/google-api-ruby-client/pull/564

remove: Unused variable

---

.github/workflows/weekly-generate-updates.yml

Doesn't make sense to regen every day if we're not going to release until the weekend. We can still kick off jobs manually if we need to get something released out of band.

chore: Switch regen job to weekly

---

google-apis-core/lib/google/api_client/client_secrets.rb

File.exists? will be removed in Ruby 3.2.
https://www.ruby-lang.org/en/news/2022/11/11/ruby-3-2-0-preview3-released/

fix: Replace `File.exists?` with `File.exist?`

---

google-apis-core/lib/google/apis/core/storage_upload.rb
google-apis-core/spec/google/apis/core/storage_upload_spec.rb

The change in #11508 introduced a significant performance
regression. It caused the HTTP client to read 8 MB chunks from the
upload source and send each chunk in separate PUT requests with a
String object instead of an IO object. This significantly slowed
upload performance since the SSL socket sends 16K at a time and
resizes the String buffer with each iteration. This caused CPU to
skyrocket since it requires allocating a new buffer and copying
existing data into that string. The garbage collector would have to
work hard to keep up.                                                                                                                                                            
To eliminate this unnecessary String resizing, wrap the read chunk in …

fix: Improve upload performance

---

google-apis-core/lib/google/apis/core/storage_upload.rb
google-apis-core/spec/google/apis/core/storage_upload_spec.rb

https://github.com/googleapis/google-api-ruby-client/pull/13283 added support for disabling upload chunking. However, when chunking is disabled, the upload attempts to read the entire file in memory instead of passing along the IO object. This often leads to out-of-memory errors when the uploaded file is large. We can significantly reduce memory by passing along the unfettered upload IO object. 
Closes #13340

storage: Optimize memory usage when upload chunk size is set to 0

---

README.md

Using the latest Content API version as Google has sunset v2, hence you'll get a 404 error when using the old example. By using v2.1 you'll get the correct results.

fix: Updated README example

---

google-apis-core/lib/google/apis/core/download.rb
google-apis-core/spec/google/apis/core/download_spec.rb

Fixes [#20389](https://github.com/googleapis/google-cloud-ruby/issues/20389)

fix(core): download with destination as pathname

---

google-apis-core/google-apis-core.gemspec
google-apis-core/lib/google/apis/core/base_service.rb
google-apis-core/spec/google/apis/core/service_spec.rb

Updates to the client base class to support universe domain.
This is the bulk of the change necessary to support universe_domain in these clients. After this is released, the generated code can be updated to pass a template in as the endpoint.
Specifically:
* Require a version of googleauth that supports universe_domain
* Perform substitution if an endpoint with the string `$UNIVERSE_DOMAIN$` is passed in
* Provide an accessor and a constructor argument for universe_domain, and provide the logic to use the environment variable and Google default as default values.
* Repeat endpoint substitution if the universe_domain is modified.
This preserves existing behavior for older clients that set static endpoints (which are now simply treated as endpoint overrides) while implementing full …

feat(core): Support for universe_domain

---

google-apis-generator/google-apis-generator.gemspec
google-apis-generator/lib/google/apis/generator/templates/gemspec.tmpl
google-apis-generator/lib/google/apis/generator/templates/service.rb.tmpl

This simply:
* Updates the google-apis-core dependency to a version that supports universe_domain in the base classes
* Passes an endpoint with a universe domain substitution into the base class instead of the google default universe endpoint.
Depends on #17131 being completed and released.

feat(generator): Support for universe_domain in generated clients

---

google-apis-core/lib/google/apis/core/base_service.rb
google-apis-core/spec/google/apis/core/service_spec.rb

Follow up to #17131. Addresses #17894.
`BaseService#root_url` is documented as an `Addressable::URI`, but in `BaseService#root_url=` it is used as if it is a `String`. This results in the following error:
```shell
google-apis-core-0.13.0/lib/google/apis/core/base_service.rb:131:in `root_url=': undefined method `include?' for an instance of Addressable::URI (NoMethodError)
if url_or_template.include? ENDPOINT_SUBSTITUTION
^^^^^^^^^
```
The tests seem to indicate that `root_url` was always allowed to be a `String` and I don't see any code prior to #17131 which required it to be an `Addressable::URI`. Therefore I am proposing updating the documentation to indicate that it can be either.

fix(core): allow BaseService#root_url to be an Addressable::URI

---

samples/cli/Gemfile
samples/cli/lib/samples/androidpublisher.rb

The gem name is misspelled. See internal issue b/293275155.

chore: Fix androidpublisher sample

---

.github/auto-approve.yml
.github/workflows/generate-updates.yml
.github/workflows/weekly-generate-updates.yml

The `YOSHI_APPROVER_TOKEN` is defunct and no longer works. This PR stops attempting to pass it into the generator. Instead, configured the auto-approve bot to handle autoapprove and automerge. Also updated the checkout action and Ruby version for those jobs.
This should not be merged until https://github.com/googleapis/repo-automation-bots/pull/5387 is merged and the auto-approve bot is redeployed.

chore: Switch generator pull request management to auto-approve

---

google-apis-core/lib/google/apis/core/http_command.rb
google-apis-core/spec/google/apis/core/http_command_spec.rb

Description: Adding Errno::ECONNRESET to Google::Apis::TransmissionError as retriable error
fixes: https://github.com/googleapis/google-api-ruby-client/issues/18902

feat(core):  add ECONNRESET error as retriable error

---

.github/workflows/release-freeze.yml
.github/workflows/release-unfreeze.yml
.toys/freeze-releases.rb

Two actions, release-freeze and release-unfreeze, that open the necessary PRs. Currently they need to be approved and merged manually. We might configure auto-approve later.

chore: Github action to help with release freezes

---

.toys/generate-updates.rb

Currently only service versions marked as "preferred" are regenerated. It appears that sometimes as new versions of a service are released, existing old versions are transitioned from "preferred" to "not preferred" status. As a result, the existing clients for those no-longer-preferred versions are no longer updated and grow stale. This PR updates the logic so that existing clients continue to be updated even if they have been moved to "not preferred". (However, a new client is still never created for a "not preferred" version.)
(See #20593)

chore: Keep updating non-preferred gems if they've already been generated

---

api_names.yaml

Resolves some generated name collisions that are blocking spanner v1 and discoveryengine v1 generation.

chore: Resolve some name collisions

---

.github/workflows/ci.yml

This is a workaround for an issue where we were getting bundler failures during CI, similar to https://github.com/rubygems/rubygems/issues/7983 except that we are on a recent bundler (2.5.22 which ships with Ruby 3.3.7) and are still getting the issue. In our case, it's failing on `syntax_suggest 2.0.1` which unlike most built-in gems, includes an executable that lives in the gem directory so the directory isn't empty.
The workaround for now is to adjust the permissions on the github actions cached gems directory so things aren't world-writable.

chore: Fix CI perms

---

.kokoro/common.cfg
.kokoro/release-generated.sh
.kokoro/release.cfg
.kokoro/release.sh

Details:
* Switched release jobs to use the dedicated release image (instead of reusing the CI image)
* No longer load any secret manager keys in the release-generated job since it doesn't need them.
* In the release job, no longer load docuploader_credentials from secret manager since ADC is sufficient.
* No longer install toys from the release scripts since it is present in the release image.
* No longer upload docs to googleapis.dev from generated client releases.

chore: Updates to release job configs

---

.github/workflows/ci.yml
google-apis-core/Gemfile
google-apis-core/lib/google/apis/core/composite_io.rb
google-apis-core/lib/google/apis/core/download.rb
google-apis-core/lib/google/apis/core/http_command.rb
google-apis-core/lib/google/apis/core/multipart.rb
google-apis-core/lib/google/apis/errors.rb
google-apis-core/spec/google/apis/core/batch_spec.rb
google-apis-core/spec/google/apis/core/composite_io_spec.rb
google-apis-core/spec/google/apis/core/service_spec.rb
google-apis-core/spec/google/apis/core/storage_upload_spec.rb
google-apis-core/spec/google/apis/core/upload_spec.rb

Ref: https://bugs.ruby-lang.org/issues/20205
Since Ruby 2.4 it is possible to run ruby with `--enable-frozen-string-literal` and it's supposed to be the default behavior in the future.
It just require some very minor change for this gem to be compatible.

Ensure compatibility with ruby --enable-frozen-string-literal

---

google-apis-core/lib/google/apis/core/base_service.rb

```
lib/google/apis/core/base_service.rb:268: warning: method redefined; discarding old client
```
This is because `attr_accessor :client` defines the `client` method, and it's later explicitly redefined.

Fix method redefined warning

---

README.md

- seen 3.1+ is still tested on CI
- 3.1 is EOL also, I'm happy to submit other PR to remove it from CI and gemspec

Update README.md with Ruby 3.1+ support info.

---

google-apis-core/lib/google/apis/core/api_command.rb
google-apis-core/spec/google/apis/core/api_command_spec.rb
google-apis-core/spec/google/apis/core/service_spec.rb

This reverts commit 0f5a074e55388a3b22db774d6701c736b514347c (pull request #22517).
There are several issues with the original pull request, notably that it sets the invocation ID as a constant, meaning ALL calls from the same Ruby VM will always use the same invocation ID. This will likely confuse any consumer of this value. (Indeed, some basic integration tests run against that code yielded weird results.)
Fortunately, the original commit used an incorrect conventional commit tag, and so did not trigger a release.

revert: setting idempotency header (#22517)

---

google-apis-core/OVERVIEW.md
google-apis-core/google-apis-core.gemspec
google-apis-core/lib/google/apis/core/base_service.rb
google-apis-core/lib/google/apis/core/batch.rb
google-apis-core/lib/google/apis/core/download.rb
google-apis-core/lib/google/apis/core/faraday_integration.rb
google-apis-core/lib/google/apis/core/http_command.rb
google-apis-core/lib/google/apis/core/storage_download.rb
google-apis-core/lib/google/apis/core/storage_upload.rb
google-apis-core/lib/google/apis/core/upload.rb
google-apis-core/lib/google/apis/options.rb
google-apis-core/spec/google/apis/core/http_command_spec.rb
google-apis-core/spec/google/apis/core/storage_upload_spec.rb

This is a often-requested step due to httpclient being largely unmaintained. We've been putting it off for a long time because it induces breaking changes for any downstream dependents (such as the Google Cloud Storage client) that rely on httpclient types. However, we're now in a situation where Google Cloud Storage client feature roadmap requires HTTP capabilities not available in httpclient. So we're going to bite the bullet and do this change.
This pull request rips out httpclient and replaces it with faraday and faraday-follow_redirects, updating usage accordingly. A few public interfaces that previously exposed httpclient types now expose equivalent Faraday types, which is technically a breaking change. We will therefore release this as a semver-major (v1.0) release. Customers who …

feat!: Replace underlying httpclient library with Faraday

---

google-apis-core/lib/google/apis/core/http_command.rb
google-apis-core/spec/google/apis/core/batch_spec.rb

fix(core): Compute and send content-length header when posting a CompositeIO

---

google-apis-core/lib/google/apis/core/download.rb
google-apis-core/lib/google/apis/core/storage_download.rb
google-apis-core/spec/google/apis/core/download_spec.rb
google-apis-core/spec/google/apis/core/storage_download_spec.rb

Related to https://github.com/googleapis/google-api-ruby-client/commit/cdf6281c73318b4467e2d99c27ebee2260750f3a#diff-81af43dded9cb6b9079107b8c2003553e23df305cfbae8c59ba69407feb09890
Fixes `NoMethodError` during streaming downloads when using Faraday 2.x with an adapter like typhoeus. 
Issue: https://github.com/googleapis/google-cloud-ruby/issues/30902 
Tested locally using `google-cloud-storage`

fix(core): Handle nil response in on_data callback for Faraday streaming
