googleapis/google-api-ruby-client

- lib/google/api_client/discovery/schema.rb
Remove `puts` trace statements
> Remove trace statements

- README.md
A couple of updates for installing pre3.
> update README.md to 0.9.pre3

- spec/google/apis/core/upload_spec.rb
> Add test for headers and length

- lib/google/apis/core/http_command.rb
- spec/google/apis/core/http_command_spec.rb
> No longer swallowing errors from block passed to execute

- lib/google/apis/core/http_command.rb
- spec/google/apis/core/http_command_spec.rb
> Allow http command to keep initial query parameters

- samples/lib/base_cli.rb
Update location if ENV['HOME'] is set in windows
> Update base_cli for windows if ENV['HOME'] is set

- samples/cli/lib/samples/bigquery.rb
> Add cli sample for bigquery api

- samples/cli/lib/samples/sheets.rb
> Add sample cli for sheets api

- lib/google/apis/errors.rb
- spec/google/apis/errors_spec.rb
> Add specs for Google::Apis::Error

- .travis.yml
- Gemfile
- Rakefile
- google-api-client.gemspec
- samples/web/Gemfile
faster build.
Test only supported version of rails.
> Travis Tweaks

- samples/cli/lib/samples/gmail.rb
Hello,
Thank you for useful gem!!
I added samples of gmail. Let me know if there's anything wrong with this PR.
Thanks!
> Add samples of gmail

- samples/cli/lib/samples/analytics.rb
Hello,
Thank you for useful gem!!!
I added a sample of realtime analytics. Let me know if there's anything wrong with this PR.
Thanks!
> add realtime analytics sample

- samples/cli/lib/samples/adsense.rb
Hello,
Thank you for useful gem!!
I added samples of adsense. Let me know if there's anything wrong with this PR.
Thanks!
> Add samples of adsense

- samples/cli/lib/samples/gmail.rb
This replace PR #535 
The sample has been added to the Gmail class, and a typo was fixed
> Add a new impersonate sample

- README.md
Add notice to top of README to highlight that this library is in maintenance mode only (i.e. not under active development).
> maintenance mode notice

- lib/google/apis/core/download.rb
Not all IO objects know how to #rewind themselves. For example, Ruby pipes (returned by `IO.pipe`) do implement #rewind, but they will throw an error if you try to call it.
```rb
rd, wr = IO.pipe
wr.rewind # Errno::ESPIPE: Illegal seek
```
But we don't need to rewind and overwrite the IO object if we didn't get the Ranged response we expected, we could instead wait out the content that has already been downloaded, and start appending again once we reached where we left off. This is what this PR does.
This allows us to use the write end of a Ruby pipe as the download destination, which enables me to implement download on-demand (to partially download only the amount bytes needed for an operation, e.g. extracting metadata that are only found at the beginning of the file).
> Recover from non-Ranged responses without rewinding

- MIGRATING.md
> Note change to normalize_unicode

- generated/google/apis/content_v2.rb
- generated/google/apis/content_v2/classes.rb
- generated/google/apis/content_v2/representations.rb
- generated/google/apis/content_v2/service.rb
Fixes #691 
@JustinBeckwith I still can't assign yoshi-* to review.
> content_v2: force regenerate

- lib/google/apis/generator/annotator.rb
> Don't crash the generator if api_names_out.yaml is absent

- Gemfile
Update version to address [vulnerability](https://nvd.nist.gov/vuln/detail/CVE-2017-17042).
> Update YARD dependency

- README.md
- google-api-client.gemspec
https://github.com/googleapis/google-api-ruby-client/issues/839
> set documentation uri to googleapis.dev location

- .yardopts
- OVERVIEW.md
- docs/api-keys.md
- docs/auth.md
- docs/client-secrets.md
- docs/getting-started.md
- docs/logging.md
- docs/media-upload.md
- docs/oauth-installed.md
- docs/oauth-server.md
- docs/oauth-web.md
- docs/oauth.md
- docs/pagination.md
- docs/performance.md
* Create a `docs` directory with guides that are linked by new top-level `OVERVIEW.md`.
* Update `.yardopts`, replacing top-level `README.md` with `OVERVIEW.md` and `docs` directory guides.
NOTE: This PR does **not** update outdated samples that use `Google::APIClient`. I will create a separate issue to update these samples for the docs in this PR.
[closes #793, closes #794, closes #795, closes #796, closes #797, closes #798, closes #799, closes #800, closes #801, closes #802]
> docs: Add OVERVIEW.md, and guides from developers.google.com

- README.md
Since I didn't see any documentation in this repo otherwise, I thought I would include my findings.
Not sure how to contribute otherwise since CONTRIBUTING.md seems to be missing.
> Added another example for Content API usage

- bin/generate-api
This is a partial rollback of #787 which I believe erroneously made the change to stop updating this file.
> Resume updating api_names_out.yaml

- lib/google/apis/core/base_service.rb
- spec/google/apis/core/service_spec.rb
> fix: Correctly handle absolute paths for simple commands

- .github/workflows/autoapprove.yml
- google-api-client.gemspec
Automatically approve autosynth PRs
> chore: Create autoapprove github action

- CHANGELOG.md
- lib/google/apis/version.rb
Initial release PR for autorelease.
Sets the version to 0.47.0, adds a changelog entry, and reformats the changelog to match what release-please and autorelease will expect.
Do not merge until #1277 is merged.
> release: Version 0.47.0

- .github/workflows/release-please.yml
> chore: Add a guard around release-please

- google-apis-generator/lib/google/apis/generator/updater.rb
Prevents some spurious regens.
> fix(generator): Fix charset used in file comparison

- google-apis-generator/google-apis-generator.gemspec
> fix(generator): Update thor dependency to allow 1.x

- script/synth.rb
- synth.py
Should fix the current synth failures.
> chore: Ensure newly created files have a reasonable owner

- google-api-client/Gemfile
- google-apis-core/Gemfile
- google-apis-generator/Gemfile
> chore: Update rake version

- README.md
> chore: Fix Drive V3 sample in the readme

- google-apis-core/lib/google/apis/core/http_command.rb
- google-apis-core/lib/google/apis/options.rb
- google-apis-core/spec/google/apis/core/http_command_spec.rb
- google-apis-core/spec/google/apis/options_spec.rb
> Add support for retry options to be configurable

- .kokoro/release-generated.cfg
- .kokoro/release.cfg
Updating the Kokoro release job for storing the artifacts released on rubygems.org in placer.
> chore(main): Added artifacts definition in release job

- google-apis-core/Gemfile
- google-apis-core/google-apis-core.gemspec
> chore(core): Remove webrick from mandatory gems

- google-apis-core/lib/google/apis/core/base_service.rb
- google-apis-core/lib/google/apis/core/storage_download.rb
- google-apis-core/spec/google/api_client/client_secrets_spec.rb
- google-apis-core/spec/google/apis/core/service_spec.rb
- google-apis-core/spec/google/apis/core/storage_upload_spec.rb
- google-apis-core/spec/google/apis/options_spec.rb
- google-apis-generator/lib/google/apis/generator/annotator.rb
- samples/cli/lib/base_cli.rb
- samples/web/app.rb
> chore: fix some typos

- google-apis-core/lib/google/apis/core/download.rb
> fix: fixes uninitialized Pathname issue

- .kokoro/common.cfg
- .kokoro/populate-secrets.sh
- .kokoro/trampoline_v2.sh
> ci: release configuration update

- .kokoro/common.cfg
> ci: remove cloud-devrel-kokoro-resources from release
